<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-VCM8IL6" failures="1" tests="8" name="Api Test Cases" time="6.913" errors="0" timestamp="2025-07-21T13:24:51 IST">
  <testcase classname="com.api.tests.LoginTest" name="validateTheEmailIdAfterLogin" time="4.568">
    <failure type="java.lang.AssertionError" message="expected [puluthii181@gmail.com] but found [puluthii11@gmail.com]">
      <![CDATA[java.lang.AssertionError: expected [puluthii181@gmail.com] but found [puluthii11@gmail.com]
at com.api.tests.LoginTest.validateTheEmailIdAfterLogin(LoginTest.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- validateTheEmailIdAfterLogin -->
  <testcase classname="com.api.tests.LoginTest" name="verifyStatusCodeForInValidEmailLogin" time="0.188"/>
  <testcase classname="com.api.tests.LoginTest" name="verifyStatusCodeForInValidPassLogin" time="0.19"/>
  <testcase classname="com.api.tests.LoginTest" name="verifyStatusCodeForValidLogin" time="0.213"/>
  <testcase classname="com.api.tests.UserProfileTest" name="updateEmail" time="0.558"/>
  <testcase classname="com.api.tests.UserProfileTest" name="updateFirstName" time="0.311"/>
  <testcase classname="com.api.tests.UserProfileTest" name="updateLastName" time="0.41"/>
  <testcase classname="com.api.tests.UserProfileTest" name="updateMobileNumber" time="0.346"/>
</testsuite> <!-- Api Test Cases -->
